### ISSUE TITLE
Number Orders returns error

### ISSUE THREAD

**Issue by lonnylot** [team-telnyx/telnyx-mock#7]
I am receiving an error while using the cURL example for [Retrieve Multiple Number Order](https://developers.telnyx.com/docs/api/v2/numbers/Number-Orders?lang=curl#listNumberOrders)

```bash
curl -X GET \
  --header "Content-Type: application/json" \
  --header "Accept: application/json" \
  --header "Authorization: Bearer KEYSUPERSECRET" \
  --globoff "http://localhost:12111/v2/number_orders?filter[phone_numbers.phone_number][]=%2B18665552368"
{
  "error": {
    "message": "Request validation error: validator 0xc000387770 failed: additional properties are not allowed: filter",
    "type": "invalid_request_error"
  }
}
```

**Comment by lucasassisrosa** [comment]
@lonnylot thanks for spotting the error. That's a `telnyx-mock` related problem regarding using query params to test. We're working on it and will provide a fix soon. https://apidev.telnyx.com/v2 should work fine though
